### ISSUE TITLE
TransientRelayError - 451 - 4.4.3 DNS lookup failed

### ISSUE THREAD

**Issue by thestick613** [slimta/python-slimta#106]
I've started getting this after i inserted a **lot** of calls to a redis instance via a unix socket file. The system can handle it, but i sometimes get this:

``````
2016-07-26 06:28:58,523.523 ERROR __init__ - log_exception: exception:ValueError:unhandled args=('filedescriptor out of range in select()',) message='filedescriptor out of range in select()' traceback=['Traceback (most recent call last):\n', '  File "/home/venv_smtpout/local/lib/python2.7/site-packages/slimta/util/dns.py", line 122, in _wait_channel\n    read_fds, write_fds, [], timeout)\n', '  File "/home/venv_smtpout/local/lib/python2.7/site-packages/gevent/select.py", line 141, in select\n    sel_results = _original_select(rlist, wlist, xlist, 0)\n', 'ValueError: filedescriptor out of range in select()\n']
Traceback (most recent call last):
  File "/home/venv_smtpout/local/lib/python2.7/site-packages/gevent/greenlet.py", line 530, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/venv_smtpout/local/lib/python2.7/site-packages/slimta/util/dns.py", line 122, in _wait_channel
    read_fds, write_fds, [], timeout)
  File "/home/venv_smtpout/local/lib/python2.7/site-packages/gevent/select.py", line 141, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
ValueError: filedescriptor out of range in select()
Tue Jul 26 06:28:58 2016 <Greenlet at 0x2ae137d96730: <bound method type._wait_channel of <class 'slimta.util.dns.DNSResolver'>>> failed with ValueError```

``````

**Comment by thestick613** [comment]
I think changing the way that `DNSResolver` works could solve this. It should use `select.poll` instead of `select.select`. `poll` is pretty standard by now, and works on mac and linux.

**Comment by thestick613** [comment]
[This](https://github.com/saghul/pycares/issues/63#issuecomment-378473420) looks like the solution.
