### ISSUE TITLE
some exception when recv unicode strings in smtp responses

### ISSUE THREAD

**Issue by thestick613** [slimta/python-slimta#88]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 134: ordinal not in range(128)
Traceback (most recent call last):
  File "/root/venv_smtpout/local/lib/python2.7/site-packages/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "/root/venv_smtpout/local/lib/python2.7/site-packages/slimta/relay/smtp/client.py", line 260, in _run
    self._handshake()
  File "/root/venv_smtpout/local/lib/python2.7/site-packages/slimta/relay/smtp/client.py", line 135, in _handshake
    self._banner()
  File "/root/venv_smtpout/local/lib/python2.7/site-packages/slimta/relay/smtp/client.py", line 49, in new_f
    ret = old_f(self, *args, **kwargs)
  File "/root/venv_smtpout/local/lib/python2.7/site-packages/slimta/relay/smtp/client.py", line 101, in _banner
    raise SmtpRelayError.factory(banner)
  File "/root/venv_smtpout/local/lib/python2.7/site-packages/slimta/relay/smtp/__init__.py", line 47, in factory
    return SmtpPermanentRelayError(reply)
  File "/root/venv_smtpout/local/lib/python2.7/site-packages/slimta/relay/smtp/__init__.py", line 61, in __init__
    super(SmtpPermanentRelayError, self).__init__('Permanent', reply)
  File "/root/venv_smtpout/local/lib/python2.7/site-packages/slimta/relay/smtp/__init__.py", line 41, in __init__
    msg = '{0} failure on {1}: {2}'.format(type, command, str(reply))
  File "/root/venv_smtpout/local/lib/python2.7/site-packages/slimta/smtp/reply.py", line 104, in __str__
    return '{0} {1}'.format(self.code, self.message)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 134: ordinal not in range(128)

**Comment by icgood** [comment]
Just FYI the unicode behavior will be _far_ better if you upgrade to Python 3. This is a fixable case, though, and should be fixed by my PR.
